name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Generate and publish weblog to GitHub Pages

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Generate weblog from Markdown files
      uses: timaa2k/markdown-weblog-builder-action@master

    - name: Commit generated HTML to gh-pages
      run: |
        git config --global user.name 'timaa2k'
        git config --global user.email 'timaa2k@users.noreply.github.com'
        git clone https://github.com/${TARGET_GITHUB_REPO} ./out && cd ./out
        git checkout -B ${TARGET_GITHUB_REF}
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${TARGET_GITHUB_REPO}
        cp -r ../result/* .
        git add -A
        git commit -m "GitHub Action: Publish weblog"
        git push
      env:
        TARGET_GITHUB_REPO: timaa2k/dev
        TARGET_GITHUB_REF: master
