name: CD

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Generate and publish weblog to GitHub Pages

    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Generate weblog from Markdown files
      uses: timaa2k/markdown-weblog-builder-action@master
      with:
        basepath: /dev

    - name: Commit generated HTML to gh-pages
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        branch=${GITHUB_REF##*/}
        target_repo=${{ github.actor }}.github.io
        if [[ ! $branch = "master" ]]; then
          target_repo=$branch
        fi
        git clone https://github.com/${{ github.actor }}/${target_repo} ./out && cd ./out
        git checkout -B master
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.actor }}/${target_repo}
        cp -r ../result/* .
        git add -A
        git commit -m "GitHub Action: Publish web log"
        git push
